## Download dos dados

In [3]:
%pip install basedosdados pandas pyarrow

^C
Note: you may need to restart the kernel to use updated packages.

In [3]:
# import basedosdados as bd

# billing_id = "a1-aedv"

# query = """
#   SELECT
#     dados.ano as ano,
#     dados.id_eleicao as id_eleicao,
#     dados.tipo_eleicao as tipo_eleicao,
#     dados.data_eleicao as data_eleicao,
#     dados.sigla_uf AS sigla_uf,
#     diretorio_sigla_uf.nome AS sigla_uf_nome,
#     dados.id_municipio AS id_municipio,
#     diretorio_id_municipio.nome AS id_municipio_nome,
#     dados.id_municipio_tse AS id_municipio_tse,
#     diretorio_id_municipio_tse.nome AS id_municipio_tse_nome,
#     dados.numero as numero,
#     dados.nome as nome,
#     dados.nome_urna as nome_urna,
#     dados.numero_partido as numero_partido,
#     dados.sigla_partido as sigla_partido,
#     dados.cargo as cargo,
#     dados.situacao as situacao,
#     dados.idade as idade,
#     dados.genero as genero,
#     dados.instrucao as instrucao,
#     dados.ocupacao as ocupacao,
#     dados.sigla_uf_nascimento as sigla_uf_nascimento,
#     dados.raca as raca
# FROM `basedosdados.br_tse_eleicoes.candidatos` AS dados
# LEFT JOIN (SELECT DISTINCT sigla,nome  FROM `basedosdados.br_bd_diretorios_brasil.uf`) AS diretorio_sigla_uf
#     ON dados.sigla_uf = diretorio_sigla_uf.sigla
# LEFT JOIN (SELECT DISTINCT id_municipio,nome  FROM `basedosdados.br_bd_diretorios_brasil.municipio`) AS diretorio_id_municipio
#     ON dados.id_municipio = diretorio_id_municipio.id_municipio
# LEFT JOIN (SELECT DISTINCT id_municipio_tse,nome  FROM `basedosdados.br_bd_diretorios_brasil.municipio`) AS diretorio_id_municipio_tse
#     ON dados.id_municipio_tse = diretorio_id_municipio_tse.id_municipio_tse
# """

# bd.read_sql(query = query, billing_project_id = billing_id)

Downloading: 100%|██████████|

,ano,id_eleicao,tipo_eleicao,data_eleicao,sigla_uf,sigla_uf_nome,id_municipio,id_municipio_nome,id_municipio_tse,id_municipio_tse_nome,...,numero_partido,sigla_partido,cargo,situacao,idade,genero,instrucao,ocupacao,sigla_uf_nascimento,raca
0,1994,1994001,eleicao ordinaria,1994-10-03,MS,Mato Grosso do Sul,None,None,None,None,...,15,PMDB,deputado estadual,None,29,None,None,None,None,None
1,1994,1994001,eleicao ordinaria,1994-10-03,BA,Bahia,None,None,None,None,...,25,PFL,deputado estadual,None,56,None,None,None,None,None
2,1994,1994001,eleicao ordinaria,1994-10-03,BA,Bahia,None,None,None,None,...,39,PP,deputado estadual,None,49,None,None,None,None,None
3,1994,1994001,eleicao ordinaria,1994-10-03,None,None,None,None,None,None,...,11,PPR,vice-presidente,None,55,feminino,None,None,None,None
4,1994,1994001,eleicao ordinaria,1994-10-03,None,None,None,None,None,None,...,15,PMDB,vice-presidente,None,51,feminino,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3375735,2020,426,eleicao ordinaria,2020-11-15,TO,Tocantins,1703107,Barrolândia,96997,Barrolândia,...,14,PTB,vereador,deferido,39,masculino,ensino fundamental incompleto,trabalhador rural,TO,parda
3375736,2020,426,eleicao ordinaria,2020-11-15,TO,Tocantins,1703107,Barrolândia,96997,Barrolândia,...,14,PTB,vereador,deferido,51,masculino,ensino medio incompleto,serralheiro,TO,branca
3375737,2020,426,eleicao ordinaria,2020-11-15,TO,Tocantins,1703107,Barrolândia,96997,Barrolândia,...,15,MDB,vereador,deferido,51,masculino,ensino medio completo,policial militar,TO,branca
3375738,2020,426,eleicao ordinaria,2020-11-15,TO,Tocantins,1703107,Barrolândia,96997,Barrolândia,...,20,PSC,vereador,deferido,51,masculino,ensino medio completo,outros,TO,parda
3375739,2020,426,eleicao ordinaria,2020-11-15,TO,Tocantins,1703107,Barrolândia,96997,Barrolândia,...,15,MDB,vereador,deferido,25,masculino,ensino fundamental completo,empresario,TO,parda

In [4]:
# df = _
# df.to_parquet("candidatos_completo.parquet")

(3375740, 23)

In [5]:
import pandas as pd
df = pd.read_parquet("candidatos_completo.parquet")

## Limpeza dos dados

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3375740 entries, 0 to 3375739
Data columns (total 23 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ano                    Int64
 1   id_eleicao             object
 2   tipo_eleicao           object
 3   data_eleicao           dbdate
 4   sigla_uf               object
 5   sigla_uf_nome          object
 6   id_municipio           object
 7   id_municipio_nome      object
 8   id_municipio_tse       object
 9   id_municipio_tse_nome  object
 10  numero                 object
 11  nome                   object
 12  nome_urna              object
 13  numero_partido         object
 14  sigla_partido          object
 15  cargo                  object
 16  situacao               object
 17  idade                  Int64
 18  genero                 object
 19  instrucao              object
 20  ocupacao               object
 21  sigla_uf_nascimento    object
 22  raca                   object
dtypes: Int64(2), dbdate(1), object(20)
memory usage: 598.8+ MB

In [10]:
for c in ["genero", "cargo", "situacao", "raca", "tipo_eleicao"]:
    print(df[c].value_counts(dropna=False), "\n")

genero
masculino    2421097
feminino      942102
None           12541
Name: count, dtype: int64

cargo
vereador               2956343
vice-prefeito           118005
prefeito                116016
deputado estadual       114686
deputado federal         54409
deputado distrital        5865
senador                   2201
governador                1611
vice-governador           1609
2º suplente senador       1040
1º suplente senador       1016
2º suplente                901
1º suplente                881
2 suplente                 350
1 suplente                 349
suplente de senador        203
presidente                  99
vice-presidente             93
vice governador             63
Name: count, dtype: int64

situacao
deferido                                         2730696
None                                              463795
indeferido                                         89777
renuncia                                           59408
indeferido com recurso                             10119
deferido com recurso                                6769
cassado                                             5013
cancelado                                           3360
sub judice                                          2829
cassado com recurso                                  828
falecido                                             725
nao conhecimento do pedido                           722
inelegivel                                           487
pedido nao conhecido                                 403
pendente de julgamento                               218
falecimento                                          218
substituto pendente de julgamento                    215
substituto majoritario pendente de julgamento         64
aguardando julgamento                                 64
pedido nao conhecido com recurso                      15
cancelado com recurso                                 12
impugnado                                              3
Name: count, dtype: int64

raca
None        1762993
branca       794667
parda        638205
preta        166365
indigena       7094
amarela        6416
Name: count, dtype: int64

tipo_eleicao
eleicao ordinaria                                       3371474
eleicoes suplementares 2008                                 619
eleicoes municipais 2020 - ap                               549
senador                                                      39
eleicao suplementar senador - mt                             35
                                                         ...
suplementar de monte azul paulista                            2
majoritaria - colinas                                         2
eleicoes suplementares 2004 - dores de guanhaes - mg          2
eleicao suplementar - serranopolis                            2
suplementar de bofete                                         2
Name: count, Length: 474, dtype: int64

In [13]:
cols_cat = [
    "tipo_eleicao", "sigla_uf", "sigla_uf_nome", "cargo", "situacao",
    "genero", "instrucao", "ocupacao", "raca", "sigla_partido",
    "sigla_uf_nascimento",
]
for c in cols_cat:
    df[c] = df[c].astype("category")

df["data_eleicao"] = pd.to_datetime(df["data_eleicao"])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3375740 entries, 0 to 3375739
Data columns (total 23 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ano                    Int64
 1   id_eleicao             object
 2   tipo_eleicao           category
 3   data_eleicao           datetime64[ns]
 4   sigla_uf               category
 5   sigla_uf_nome          category
 6   id_municipio           object
 7   id_municipio_nome      object
 8   id_municipio_tse       object
 9   id_municipio_tse_nome  object
 10  numero                 object
 11  nome                   object
 12  nome_urna              object
 13  numero_partido         object
 14  sigla_partido          category
 15  cargo                  category
 16  situacao               category
 17  idade                  Int64
 18  genero                 category
 19  instrucao              category
 20  ocupacao               category
 21  sigla_uf_nascimento    category
 22  raca                   category
dtypes: Int64(2), category(11), datetime64[ns](1), object(9)
memory usage: 357.4+ MB

In [15]:
df.head()

,ano,id_eleicao,tipo_eleicao,data_eleicao,sigla_uf,sigla_uf_nome,id_municipio,id_municipio_nome,id_municipio_tse,id_municipio_tse_nome,...,numero_partido,sigla_partido,cargo,situacao,idade,genero,instrucao,ocupacao,sigla_uf_nascimento,raca
0,1994,1994001,eleicao ordinaria,1994-10-03,MS,Mato Grosso do Sul,None,None,None,None,...,15,PMDB,deputado estadual,NaN,29,NaN,NaN,NaN,NaN,NaN
1,1994,1994001,eleicao ordinaria,1994-10-03,BA,Bahia,None,None,None,None,...,25,PFL,deputado estadual,NaN,56,NaN,NaN,NaN,NaN,NaN
2,1994,1994001,eleicao ordinaria,1994-10-03,BA,Bahia,None,None,None,None,...,39,PP,deputado estadual,NaN,49,NaN,NaN,NaN,NaN,NaN
3,1994,1994001,eleicao ordinaria,1994-10-03,NaN,NaN,None,None,None,None,...,11,PPR,vice-presidente,NaN,55,feminino,NaN,NaN,NaN,NaN
4,1994,1994001,eleicao ordinaria,1994-10-03,NaN,NaN,None,None,None,None,...,15,PMDB,vice-presidente,NaN,51,feminino,NaN,NaN,NaN,NaN

In [16]:
df.to_parquet("candidatos_completo.parquet")